<?php

$items = $this->getCollection();

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
    <div>	
    <a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('item','add');?>" class="main999">ADD ITEM</a>
    </div>
	<table class="table table-dark table-striped-columns">
		<tr>
			<td>Entity Id</td>
			<td>SKU</td>
			<td>Entity Type Id</td>
			<td>Status</td>
			<td>Created At</td>
			<td>Updated At</td>
			<td>Edit</td>
		</tr>

		 <?php foreach ($items->getData() as $item): ?>

		<tr>
			<td><?php echo $item->entity_id;?></td>
			<td><?php echo $item->sku;?></td>
			<td><?php echo $item->entity_type_id;?></td>
			<td><?php echo $item->status;?></td>
			<td><?php echo $item->created_at;?></td>
			<td><?php echo $item->updated_at;?></td>
			<td><a href="  <?php echo $this->getUrl('item','edit',array('id' =>  $item->entity_id));?>">EDIT</td>
		</tr>
			
		<?php endforeach; ?>
	</table>

</body>
</html>