<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
	<header>
		
		<div class="navbar" style="background-color: #e3f2fd;">
			<a href="index.php?c=product&a=index" class="btn btn-primary">Product</a>
			<a href="index.php?c=category&a=index" class="btn btn-info" >Category</a>
			<a href="index.php?c=customer&a=index" class="btn btn-primary" >Customer</a>
			<a href="index.php?c=salesman&a=index" class="btn btn-info" >Salesman</a>
			<a href="index.php?c=vendor&a=index" class="btn btn-primary">Vendor</a>
			<a href="index.php?c=shipping&a=index" class="btn btn-info" >Shipping_method</a>
			<a href="index.php?c=payment&a=index" class="btn btn-primary" >Payment_method</a>
			<a href="index.php?c=admin&a=index" class="btn btn-info" >Admin</a>
			<a href="index.php?c=eav_attribute&a=grid" class="btn btn-info" >Eav Attribute</a>
			<a href="index.php?c=item&a=index" class="btn btn-info" >Item</a>
			<a href="index.php?c=order&a=grid" class="btn btn-info" >Order</a>
		</div>
	</header>

</body>
</html>