<?php
$products = $this->getCollection();
?>

    <div class="title9">
    	<div class="main9">
    	MANAGE PRODUCTS
    	</div>
    
    <div class="main99">
    	<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('product','add');?>" class="main999">ADD PRODUCT</a>
    </div>
    </div>

   <table class="table table-dark table-striped-columns">

   	     <tr>
   	     	<td>product_id</td>
   	     	<td>name</td>
   	     	<td>cost</td>
   	     	<td>SKU</td>
   	     	<td>price</td>
   	     	<td>quantity</td>
   	     	<td>description</td>
   	     	<td>status</td>
   	     	<td>color</td>
   	     	<td>material</td>
   	     	<td>created_at</td>
   	     	<td>updated_at</td>
   	     	<td>media</td>
   	     	<td>EDIT</td>
   	     	<td>DELETE</td>
   	     </tr>
           <?php  if (!$products):?> 
              <tr>
                 <td>No records available.</td>
              </tr>
           <?php else:?>
   	      <?php foreach ($products->getData() as $product): ?>
            <tr>
            	<td><?php echo $product->product_id?></td>
            	<td><?php echo $product->name?></td>
            	<td><?php echo $product->cost?></td>
            	<td><?php echo $product->SKU?></td>
            	<td><?php echo $product->price?></td>
            	<td><?php echo $product->quantity?></td>
            	<td><?php echo $product->description?></td>
               <td><?php echo $product->getStatusText($product->status );?></td>
            	<td><?php echo $product->color?></td>
            	<td><?php echo $product->material?></td>
            	<td><?php echo $product->created_at?></td>
            	<td><?php echo $product->updated_at?></td>
            	<td><a href="<?php echo $this->getUrl('product_media','grid',array('product_id' =>  $product->product_id));?>">media</td>
               
                  <td><a href="  <?php echo $this->getUrl('product','edit',array('product_id' =>  $product->product_id));?>">EDIT</td>
            	<td><a href="<?php echo $this->getUrl('product','delete',array('product_id' =>  $product->product_id));?>">DELETE</td>
            </tr>
   	     	
   	     <?php endforeach; ?>
           <?php endif; ?>
   </table>
