<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link rel="stylesheet" type="text/css" href="Skin/css/mediaadd.css">
</head>
<body>
<form action="http://localhost/newmvc-akshayFultariya/index.php?c=product&a=upload" method="post" enctype="multipart/form-data">
  Select file to upload:
  <input type="file" name="file" id="fileToUpload">
  <input type="submit" value="Upload" name="submit">
</form>

</body>
</html>