<?php

$shippingMethod = $this->getRow();
// print_r($shippingMethod);
// die();

?>
	<form action="<?php echo $this->getUrl('shipping','save');?>" method = "post">
		<div class="content9">
			<div class="add19">
				EDIT SHIPPING
			</div>
			<div class="add29">
				<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('shipping','grid',[],true);?>" class="add39">Cancel</a>
				<button type="submit" class="add39">Save</button>
			</div>
		</div>
		<div class="head9">
			SHIPPING INFORMATION
		</div>

		<table class="table table-dark table-striped-columns">
			<tr>
				<td>name</td>
				<td><input type="text" name="shipping[name]" value="<?php echo $shippingMethod->name;?>" class = "addi9">
				</td>
			</tr>
			<tr>
				<td>amount</td>
				<td><input type="text" name="shipping[amount]" value="<?php echo $shippingMethod->amount;?>" class = "addi9">
				</td>
			</tr>
				<tr>
		<td>Status</td>
		<td>
		<select name="shipping[status]">
			<?php foreach ($shippingMethod->getResource()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $shippingMethod->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>

	</td>
	</tr>
	<?php foreach ($shippingMethod->getattributes() as $key => $attribute): ?>
		<tr>
			<td><?php echo $attribute->name;?></td>
			<td>
				<?php $this->getLayout()->createBlock('Eav_Attribute_Inputtype')->setAttributes($attribute)->setRow($shippingMethod)->render(); ?>
			</td>
		</tr>
	<?php endforeach;?>
		</table>
	</form>
