<?php

$shipping_methods = $this->getCollection()->getData();

?>
	<?php require_once 'View/html/header.phtml';?>
	<div class="title9">
		<div class="main9">
			MANAGE SHIPPING
		</div>
		
		<div class="main99">
			<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('shipping','add');?>" class="main999">ADD SHIPPING</a>
		</div>
	</div>
	<table class="table table-dark table-striped-columns">
		<tr>
			<td>shipping_id</td>
			<td>name</td>
			<td>amount</td>
			<td>status</td>
			<td>created_at</td>
			<td>updated_at</td>
			<td>EDIT</td>
			<td>DELETE</td>
		</tr>
		<?php if (!$shipping_methods):?>
		<tr>
			<td>No records available.</td>
		</tr>
		<?php else:?>
		<?php foreach ($shipping_methods as $shipping_method): ?>
		<tr>			
			<td><?php echo $shipping_method->shipping_id?></td>
			<td><?php echo $shipping_method->name?></td>
			<td><?php echo $shipping_method->amount?></td>
			<td><?php echo $shipping_method->getStatusText($shipping_method->status );?></td>
			<td><?php echo $shipping_method->created_at?></td>
			<td><?php echo $shipping_method->updated_at?></td>
			<td><a href="<?php echo $this->getUrl('shipping','edit',array('shipping_id' =>  $shipping_method->shipping_id));?>">EDIT</td>
			<td><a href="<?php echo $this->getUrl('shipping','delete',array('shipping_id' =>  $shipping_method->shipping_id));?>">DELETE</td>
		</tr>

		<?php endforeach; ?>
		<?php endif;?>	
	</table>
