<?php

$admin = $this->getRow();
?>
<form method="post" action="<?php echo $this->getUrl('admin','save')?>" id="admin-form">
<table width="100%" border="1px">
	<tr>
		<td>Email</td>
		<td><input type="text" name="admin[email]" value="<?php echo $admin->email ?>"></td>
	</tr>
	<tr>
		<td>Password</td>
		<td><input type="text" name="admin[password]" value="<?php echo $admin->password ?>"></td>
	</tr>
	<tr>
		<td>Status</td>
		<td>
		<select name="admin[status]">
			<?php foreach ($admin->getResource()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $admin->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>
	</td>
	</tr>

	<?php foreach ($admin->getattributes() as $key => $attribute): ?>
		<tr>
			<td><?php echo $attribute->name;?></td>
			<td>
				<?php $this->getLayout()->createBlock('Eav_Attribute_Inputtype')->setAttributes($attribute)->setRow($admin)->render(); ?>
			</td>
		</tr>
	<?php endforeach;?>	
	<div class="add29">
				<a type="button" class="btn btn-primary" onclick="ajax.setUrl('<?php echo $this->getUrl('admin','grid',[],true);?>').call();" class="add39">Cancel</a>
				<button type="button" class="btn btn-primary"  onclick="ajax.setUrl('<?php echo $this->getUrl('admin','save')?>').setForm('admin-form').call();">Save</button>
			</div>
</table>
</form>