<?php

$admins = $this->getCollection()->getData();

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>

<table class="table table-hover">
	<tr>
		<td>
			<a type="button" class="btn btn-primary" href="<?php  echo $this->getUrl('admin','add');?>">ADD</a>
		</td>
	</tr>
</table>

<table class="table table-hover">
	<tr>
		<td>Admin Id</td>
		<td>Email</td>
		<td>Status</td>
		<td>Created At</td>
		<td>Updated At</td>
		<td>Edit</td>
	</tr>

	<?php if (!$admins):?>
		<tr>
			<td>No records available.</td>
		</tr>
	<?php else:?>
		<?php foreach($admins as $admin):?>
			<tr>
				<td><?php echo $admin->admin_id;?></td>
				<td><?php echo $admin->email;?></td>
				<!-- <td><?php //echo $admin->status;?></td> -->
				<td><?php echo $admin->getStatusText($admin->status );?></td>
				<td><?php echo $admin->created_at;?></td>
				<td><?php echo $admin->updated_at;?></td>
				<td><a href="<?php echo $this->getUrl('admin','edit',['id'=>$admin->admin_id])?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl('admin','delete',['id'=>$admin->admin_id])?>">Delete</a></td>
			</tr>
		<?php endforeach; ?>
	<?php endif;?>
</table>
</html>