<?php
$s = $this->getCollection();
// $salesmanId = $this->salesmanId; 

// $salesmen = $this->salesmen;
// $salesmanPrices = $this->salesmanPrices;

$salesmanId = $s[0]; 

$salesmen = $s[1]; 
$salesmanPrices = $s[2]; 
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
	<?php require_once 'View/html/message.phtml';?>
	
	<form method="post" action = "<?php echo $this->getUrl('salesman_price', 'update', ['salesman_id' => $salesmanId]);?>">
	<table class="table table-dark table-striped-columns">

		<select>
			<option>select salesman</option>
			<?php foreach ($salesmen->getData() as $salesman): ?>
				
			<option value="<?php echo $salesman->salesman_id;
							if($salesman->salesman_id == $id){
								echo "selected";
								}?>"><?php echo $salesman->first_name?></option>
			<?php endforeach ?>
			<input type="submit" name="save">
		</select>

		<!-- <button>UPDATE</button> -->
		<button type="submit" class="add39">Update</button>

		<tr>
			<td>product_id</td>
			<td>name</td>
			<td>sku</td>
			<td>cost</td>
			<td>price</td>
			<td>s_price</td>
			<td>remove</td>
		</tr>

		<?php foreach ($salesmanPrices->getData() as $salesman_price): ?>
			
		<tr>
			<td><?php echo $salesman_price->product_id ?></td>
			<td><?php echo $salesman_price->name ?></td>
			<td><?php echo $salesman_price->SKU ?></td>
			<td><?php echo $salesman_price->cost ?></td>
			<td><?php echo $salesman_price->price ?></td>
			<td><input type="number" name="s_price[<?php echo $salesman_price->product_id;?>]" value = "<?php echo $salesman_price->salesman_price?>" ></td>
			<td><a href="<?php echo $this->getUrl('salesman','delete',['salesman_id' => $price['product_id']])?>">delete</a>
			</td>
			
		</tr>
		<?php endforeach ?>

		</table>
</form>
</body>
</html>