<?php

$payment = $this->getRow();

?>
	<form action="<?php echo $this->getUrl('payment','save');?>" method = "post">
		<div class="content9">
			<div class="add19">
				EDIT PAYMENT
			</div>	
			<div class="add29">
				<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('payment','grid',[],true);?>" class="add39">Cancel</a>
				<button type="submit" class="add39">Save</button>
			</div>
		</div>
		<div class="head9">
			PAYMENT INFORMATION
		</div>
		<table class="table table-dark table-striped-columns">
			<tr>
				<td>name</td>
				<td><input type="text" name="payment[name]" value="<?php echo $payment->name;?>" class="addi9"></td>
			</tr>
		<td>Status</td>
		<td>
		<select name="payment[status]">
			<?php foreach ($payment->getResource()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $payment->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>
	</td>
		<!-- <td><input type="text" name="admin[status]" value="<?php echo $admin->status ?>"></td> -->
	</tr>
	<?php foreach ($payment->getattributes() as $key => $attribute): ?>
		<tr>
			<td><?php echo $attribute->name;?></td>
			<td>
				<?php $this->getLayout()->createBlock('Eav_Attribute_Inputtype')->setAttributes($attribute)->setRow($payment)->render(); ?>
			</td>
		</tr>
	<?php endforeach;?>
		</table>
	</form>
