<?php

$attributes = $this->getCollection();

?>

    <div class="title9">
    	<div class="main9">
    	MANAGE AttributeS
    	</div>
    
    <div class="main99">
    	<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('eav_attribute','add');?>" class="main999">ADD attribute</a>
    </div>
    </div>

   <table class="table table-dark table-striped-columns">

   	     <tr>
   	     	<td>Attribute_id</td>
   	     	<td>entity_id</td>
   	     	<td>code</td>
   	     	<td>backend_type</td>
   	     	<td>name</td>
   	     	<td>status</td>
   	     	<td>backend_model</td>
   	     	<td>input_type</td>
   	     	<td>EDIT</td>
   	     	<td>DELETE</td>
   	     </tr>
           <?php  if (!$attributes):?> 
              <tr>
                 <td>No records available.</td>
              </tr>
           <?php else:?>
   	      <?php foreach ($attributes->getData() as $attribute): ?>
            <tr>
            	<td><?php echo $attribute->attribute_id?></td>
            	<td><?php echo $attribute->entity_type_id?></td>
            	<td><?php echo $attribute->code?></td>
            	<td><?php echo $attribute->backend_type?></td>
            	<td><?php echo $attribute->name?></td>
                <td><?php echo $attribute->getStatusText($attribute->status );?></td>
            	<td><?php echo $attribute->backend_model?></td>
            	<td><?php echo $attribute->input_type?></td>
                <td><a href="  <?php echo $this->getUrl('eav_attribute','edit',array('attribute_id' =>  $attribute->attribute_id));?>">EDIT</td>
            	<td><a href="<?php echo $this->getUrl('eav_attribute','delete',array('attribute_id' =>  $attribute->attribute_id));?>">DELETE</td>
            </tr>
   	     	
   	     <?php endforeach; ?>
           <?php endif; ?>
   </table>
