<?php

$a = $this->getCollection();
$quotes = $a[0];
$customers = $a[1];


?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
	<select name="">
		<?php foreach ($customers->getData() as $customer) :?>
		     <option><?php echo $customer->mobile?><?php echo $customer->email?></option>
		<?php endforeach;?>
	</select>
    <div>	
    <a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('quote','add');?>" class="main999">ADD QUOTE</a>
    </div>
	<table class="table table-dark table-striped-columns">
		<tr>
			<td>BILLING ADDRERSS</td>
			<td>SHIPPING ADDRESS</td>
		</tr>
		<tr>
			<td>
				<tr></tr>
			</td>
			<td></td>
		</tr>


	</table>

</body>
</html>