<?php

$cust = $this->getRow();
$customer = $cust[0];
// $billingAddress = $cust[1];
// // echo "<pre>";
// // print_r($billingAddress);
// // die();
// $shippingAddress = $cust[2];
$billingAddress = $this->getBillingAddress();
$shippingAddress = $this->getShippingAddress();

?>
	<form action="<?php echo $this->getUrl('customer','save');?>" method="post" id="customer-form">
		<div class="content9">
			<div class="add19">
				EDIT CUSTOMER				
			</div>
			<div class="add29">
				<a type="button" class="btn btn-primary" onclick="ajax.setUrl('<?php echo $this->getUrl('customer','grid',[],true);?>').call();" class="add39">Cancel</a>
				<button type="button" class="btn btn-primary"  onclick="ajax.setUrl('<?php echo $this->getUrl('customer','save')?>').setForm('customer-form').call();">Save</button>
			</div>
		</div>
		<div class="head9">
			CUSTOMER INFORMATION
		</div>
		<table class="table table-dark table-striped-columns">
			<tr>
				<td>first_name</td>
				<td><input type="text" name="customer[first_name]" value="<?php echo $customer->first_name;?>" class="addi9"></td>
			</tr>
			<tr>
				<td>last_name</td>
				<td><input type="text" name="customer[last_name]" value=" <?php echo $customer->last_name; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>email</td>
				<td><input type="text" name="customer[email]" value=" <?php echo $customer->email; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>gender</td>
				<td><input type="text" name="customer[gender]" value=" <?php echo $customer->gender; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>mobile</td>
				<td><input type="text" name="customer[mobile]" value=" <?php echo $customer->mobile; ?>" class="addi9"></td>
			</tr>
			<tr>
		<td>Status</td>
		<td>
		<select name="customer[status]">
			<?php foreach ($customer->getResource()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $customer->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>
	</td>
	</tr>
	
		</table>
		<div class="head9">
		BILLING INFORMATION
	</div>
	<table class="table table-hover">
		<tr>
			<td>address</td>
			<td><input type="text" name="billingAddress[address]"  class="addi9" value="<?php echo $billingAddress->address;?>"></td>
		</tr>
		<tr>
			<td>city</td>
			<td><input type="text" name="billingAddress[city]"  class="addi9" value="<?php echo $billingAddress->city;?>"></td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="billingAddress[state]"  class="addi9" value="<?php echo $billingAddress->state;?>"></td>
		</tr>
		<tr>
			<td>country</td>
			<td><input type="text" name="billingAddress[country]"  class="addi9" value="<?php echo $billingAddress->country;?>"></td>
		</tr>
		<tr>
			<td>zip_code</td>
			<td><input type="text" name="billingAddress[zip_code]"  class="addi9" value="<?php echo $billingAddress->zip_code;?>"></td>
		</tr>
	
	</table>

	<div class="head9">
		SHIPPING INFORMATION
	</div>

	<table class="table table-hover">
		<tr>
			<td>address</td>
			<td><input type="text" name="shippingAddress[address]"  class="addi9" value="<?php echo $shippingAddress->address;?>"></td>
		</tr>
		<tr>
			<td>city</td>
			<td><input type="text" name="shippingAddress[city]"  class="addi9" value="<?php echo $shippingAddress->city;?>"></td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="shippingAddress[state]"  class="addi9" value="<?php echo $shippingAddress->state;?>"></td>
		</tr>
		<tr>
			<td>country</td>
			<td><input type="text" name="shippingAddress[country]"  class="addi9" value="<?php echo $shippingAddress->country;?>"></td>
		</tr>
		<tr>
			<td>zip_code</td>
			<td><input type="text" name="shippingAddress[zip_code]"  class="addi9" value="<?php echo $shippingAddress->zip_code;?>"></td>
		</tr>
	</table>
	</form>
