<?php

$categorys = $this->getCollection()->getData();

?>
	<?php require_once 'View/html/header.phtml';?>
	<div class="title9">
	  <div class="main9">
		MANAGE CATEGORY
	  </div>
	  <div class="main99">
		<a type="button" class="btn btn-primary" href="<?php echo $this->getUrl('category','add');?>" class="main999">ADD CATEGORY</a>
	  </div>
    </div>
    <table class="table table-dark table-striped-columns">
    	<tr>
    		<td>category_id</td>
    		<td>name</td>
    		<td>description</td>
    		<td>status</td>
    		<td>created_at</td>
    		<td>updated_at</td>
    		<td>Edit</td>
    		<td>Delete</td>
    	</tr>
    	<?php if (!$categorys):?>
		<tr>
			<td>No records available.</td>
		</tr>
		<?php else:?>
    	<?php foreach ($categorys as $category):?>
    		<tr>
    			<td><?php echo $category->category_id ?></td>
    			<td><?php echo $category->getPathCategories($category->category_id); ?></td>
    			<td> <?php echo $category->description ?></td>
                <td><?php echo $category->getStatusText($category->status );?></td>
    			<td> <?php echo $category->created_at ?></td>
    			<td> <?php echo $category->updated_at ?></td>
    			<td><a href="<?php echo $this->getUrl('category','edit',array('category_id' =>  $category->category_id));?>">EDIT</td>
    			<td><a href="<?php echo $this->getUrl('category','delete',array('category_id' =>  $category->category_id));?>">DELETE</td>
	    	</tr>
	    <?php endforeach;?>
	    <?php endif;?>
    </table>
