<?php
$rows = $this->getCollection();
if (!$rows) {
	echo "No data found";
}
else{
$rows = $this->getCollection()->getData();
}

?>
	<div class="title9">
		<div class="main9">
			<?php echo $this->getTitle();?>
		</div>
		<div class="main99">
			<?php foreach ($this->getButtons() as $key => $button): ?>
			<a type="button" class="btn btn-primary" onclick="ajax.setUrl('<?php echo $button['url'];?>').call()"><?php echo $button['title']?></a>
			<?php endforeach;?>
		</div>
	</div>
	<table class="table table-dark table-striped-columns">
		<tr>
			<?php foreach ($this->getColumns() as $key => $column): ?>
			<td><?php echo $column['title'];?></td>
			<?php endforeach;?>
			<?php foreach ($this->getActions() as $key => $action): ?>
			<td><?php echo $action['title'];?></td>
			<?php endforeach;?>
		</tr>
		<?php if (!$rows):?>
		<tr>
			<td>No records available.</td>
		</tr>
		<?php else:?>
		 <?php foreach ($rows as $row): ?>
		 	<tr>
			<?php foreach ($this->getColumns() as $key => $column): ?>
		 		<td> <?php echo $this->getColumnValue($row,$key); ?></td>
			<?php endforeach;?>
			<?php foreach ($this->getActions() as $key => $action): ?>
		 		
		 		<td>
		 			<input name="add" value="<?php echo $action['title'];?>" type="button" onclick="ajax.setUrl('<?php $method = $action['method']; echo $this->$method($row,$key);?>').call()" name="">
		 		</td>	
			<?php endforeach;?>
		 		</tr>
			
		<?php endforeach ?>
		<?php endif;?>
	</table>
